global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'todo-api'
    static_configs:
      - targets: ['api:3000'] # Le nom du service dans docker-compose
    metrics_path: '/metrics'  # Point d'accès pour les métriques OpenTelemetry